### ISSUE TITLE
Make default scope and namespace optional

### ISSUE THREAD

**Issue by MrHash** [daikon-cqrs/config#3]

**Comment by shrink0r** [comment]
When using the short path notation e.g. $config->get("foobar") an exception would be raised then, in cases where no default scope and namespace have been provided. Is that ok?

**Comment by MrHash** [comment]
yes that's ok, or perhaps null?

**Comment by shrink0r** [comment]
Check, I guess null is a bit more gracefull.

**Comment by shrink0r** [comment]
Namespace concept has been removed as a whole.
Default scope support has been removed too.
